SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS User;
CREATE TABLE User (
	user_id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(128) NOT NULL,
	password VARCHAR(128) NOT NULL,
	name VARCHAR(128),
	surname VARCHAR(128),
	position VARCHAR(128),
	PRIMARY KEY(user_id)
) ENGINE=INNODB;

DROP TABLE IF EXISTS Staff;
CREATE TABLE Staff (
	staff_id INT NOT NULL,
	FOREIGN KEY (staff_id)
	REFERENCES User(user_id)
	ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

DROP TABLE IF EXISTS Business_Partner;
CREATE TABLE Business_Partner (
	partner_id INT NOT NULL,
	represents VARCHAR(128) NOT NULL,
	FOREIGN KEY (partner_id)
	REFERENCES User(user_id)
	ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

DROP TABLE IF EXISTS Meeting;
CREATE TABLE Meeting (
	meeting_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	creator_id INT NOT NULL,
	date DATE NOT NULL,
	end_time TIME NOT NULL,
	start_time TIME NOT NULL,
	FOREIGN KEY (creator_id)
	REFERENCES Staff(staff_id)
	ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;

DROP TABLE IF EXISTS Team;
CREATE TABLE Team (
	name VARCHAR(128) NOT NULL,
	status TINYINT NOT NULL,
	PRIMARY KEY(name)
) ENGINE=INNODB;


DROP TABLE IF EXISTS Team_In;
CREATE TABLE Team_In (
	team_name VARCHAR(128),
	staff_id INT,
	FOREIGN KEY (team_name) REFERENCES Team(name)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (staff_id) REFERENCES Staff(staff_id)
	ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

DROP TABLE IF EXISTS Participate;
CREATE TABLE Participate (
	meeting_id INT,
	user_id INT,
	FOREIGN KEY (meeting_id) REFERENCES Meeting(meeting_id)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES User(user_id)
	ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

DROP TABLE IF EXISTS Meeting_Payment;
CREATE TABLE Meeting_Payment (
	meeting_id INT,
	team_name VARCHAR(128),
	amount INT,
	status TINYINT,
	FOREIGN KEY (meeting_id) REFERENCES Meeting(meeting_id)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (team_name) REFERENCES Team(name)
	ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;

DROP TABLE IF EXISTS Available_Resource;
CREATE TABLE Available_Resource (
	id INT NOT NULL AUTO_INCREMENT,
	room_no SMALLINT,
	capacity SMALLINT,
	address VARCHAR(128),
	building_name VARCHAR(128),
	PRIMARY KEY(id)
) ENGINE=INNODB;

DROP TABLE IF EXISTS Booking;
CREATE TABLE Booking (
	meeting_id INT,
	resource_id INT,
	FOREIGN KEY (meeting_id) REFERENCES Meeting(meeting_id)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (resource_id) REFERENCES Available_Resource(id)
	ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;


DROP TABLE IF EXISTS Facility;
CREATE TABLE Facility (
	name VARCHAR(128) NOT NULL,
	cost FLOAT NOT NULL,
	PRIMARY KEY(name)
) ENGINE = INNODB;

DROP TABLE IF EXISTS Facility_In;
CREATE TABLE Facility_In (
	facility_name VARCHAR(128),
	resource_id INT,
	FOREIGN KEY (facility_name) REFERENCES Facility(name)
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (resource_id) REFERENCES Available_Resource(id)
	ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;


SET FOREIGN_KEY_CHECKS=1;
