
/* User */

INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Lenore","DTN33UAZ8KD","Debra, Ivan","Moran","A Feugiat Tellus Corp."),("Madonna","PYL63HXW6JU","John, Sylvester","Dorsey","Magna Tellus LLC"),("Christen","EOX00TTO6TJ","Ayanna, Hedda","Hicks","A Ltd"),("Jasper","SAE50BQH1FQ","Willa, Blaze","Workman","Enim Mauris Industries"),("Jillian","GZL03JER0OB","David, Autumn","Knapp","Ipsum Institute"),("Rahim","KOZ58JYW0QV","Cheryl, Lenore","Salas","Erat Institute"),("Angela","GIZ49IIC8TO","Nora, Oprah","Suarez","Integer Industries"),("Regan","SVJ59PFY3SF","Quinn, Phelan","Cash","Dis Consulting"),("Robin","KRX74UHT2VW","Clarke, Reece","Whitaker","Orci Limited"),("Isaiah","XJV34EKN5VL","Abel, Grady","Snow","In Lobortis Institute");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Salvador","JQJ99ILL5ZN","Noble, Emmanuel","Oneil","Vestibulum Limited"),("Jayme","ADX50APF9QS","Regina, Camille","Freeman","Primis In Faucibus Foundation"),("Finn","CVE72YYC0DN","Amela, Ray","Fuller","Interdum Enim Non Corp."),("Lacota","EUI09FHV9JI","Irma, Nero","Kim","Elit Pellentesque A Corp."),("Norman","HRJ83MCW7YD","Talon, Ivor","Hoffman","Aliquam Limited"),("Macon","DOP88TEG2WG","Hermione, Kristen","Tanner","Accumsan Ltd"),("Acton","GEJ67LIN4NE","Maryam, Emi","Rich","Non Egestas A Inc."),("Kitra","JAQ47QKZ1YR","Ferdinand, Damon","Ware","Pellentesque Eget Foundation"),("Edan","JSF35EDU7YT","Alana, Emerald","Key","Tincidunt Associates"),("Chancellor","WDV65SCV9WR","Cherokee, Cadman","Dillon","Nam Nulla Foundation");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Juliet","SHF82XEY5YD","Eleanor, Ulysses","Santos","Mauris Consulting"),("Griffith","ZFT15WWC6WN","Reece, Logan","Tate","Volutpat Ornare Facilisis Associates"),("Whoopi","ATN44CXK3DZ","Hu, Phelan","Jensen","Est Institute"),("Jesse","HRJ93MAB7EH","Rashad, Laura","Harrington","Non Massa Consulting"),("Calvin","XHP50OSL8PS","Noah, Aquila","Delgado","Pharetra Quisque Inc."),("Mufutau","NMI85AWR9BP","Robin, Marvin","Gates","Vehicula Risus Nulla Foundation"),("Selma","VVQ03JGP0ZS","Carter, Brielle","Heath","Nec Diam Inc."),("Whoopi","QVL01ZRA8XS","Allistair, Curran","Thompson","At Velit Pellentesque Corp."),("Daphne","UEF94TUF4VN","Dylan, Thomas","Levine","Blandit Corporation"),("Mona","WIB55UPX4EL","Gray, Sheila","Palmer","Augue Porttitor Interdum PC");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Adrian","OQZ39JCD8TS","Oliver, Sydnee","Franks","Lacinia Inc."),("Natalie","LQD48GWH2VE","Faith, Aurora","Bolton","Rutrum Urna Ltd"),("Nero","GYL34CUE1HM","Nicole, Cheryl","Thompson","Ipsum Dolor Sit Institute"),("Orson","REZ28EBB3VL","Todd, Aretha","Herring","Nulla Corp."),("Katelyn","XER14AAV0LZ","Jeanette, Basil","Chavez","Velit Consulting"),("Jerome","EOP51DPN2TX","Shelly, Dai","Gates","Proin Ultrices Duis Corp."),("Rose","ZJM57OJA3DX","Stacy, Colt","Morgan","Nunc Interdum Incorporated"),("Bevis","IJH43WMA2SA","Xanthus, Edward","Drake","Vel Nisl Company"),("Kamal","KDO69LHJ0CH","Demetria, Elizabeth","Sellers","Lorem Tristique Aliquet LLC"),("Kiayada","OJM95GXN8YG","Haviva, Randall","Orr","Ac Mattis Foundation");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Paul","PSU28LBL2ID","Ginger, Patrick","Ramirez","Ultrices Corporation"),("Autumn","VPX97RDC0OW","Debra, Hiroko","Ruiz","Eu Nulla At PC"),("Ivana","MXY99BDD3EE","Jameson, Sara","Bird","Arcu Et Incorporated"),("Gil","OLV59UMM7DL","Hedda, Daniel","Cox","Auctor Non Company"),("Hedda","HBP48TJC2OM","Carissa, Petra","Fernandez","Dolor Elit Pellentesque Ltd"),("Quintessa","BXR35OGQ2YM","Jocelyn, Prescott","Bowman","Vestibulum Accumsan Neque LLP"),("Kasper","UEU84AZA3UM","Frances, Aristotle","Galloway","Lorem Luctus LLP"),("Charity","KJK11ALD2GH","Upton, Dakota","Combs","Augue Porttitor Incorporated"),("Xander","LQZ86CRU1LD","Galena, Jael","Morales","Sollicitudin Corp."),("Inga","WWH54TWZ5SM","Tiger, Kylie","Prince","Per Conubia Nostra Inc.");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Owen","XBA01UKK4CR","Camden, Yardley","Sanchez","Tristique Ac Eleifend Consulting"),("Rylee","SZE54FLZ8WW","Brock, Sharon","Juarez","In Consequat Associates"),("Armando","PAN34KIZ4IL","Fallon, Conan","Bentley","Penatibus Et Magnis Institute"),("Stephen","HVK40WFN4SJ","May, Driscoll","Sweeney","Porttitor Tellus Non Limited"),("Plato","AEI57XSB3HB","Madeson, Lewis","Pennington","Lorem Associates"),("Hadley","QRP74UYV8VK","Malik, Evan","Dominguez","Libero Company"),("Wayne","PFH74RQG4PQ","Blaine, Travis","Hoover","Ligula Industries"),("Stephanie","JMY06KDK7RA","Mariko, Quemby","Bowman","Lobortis Consulting"),("Desiree","YYT79SOI1IR","Lucian, Lunea","Mccormick","At Lacus Consulting"),("Akeem","KAP42CCU3MX","Nina, Felix","Quinn","Aenean Gravida Nunc Limited");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Yvette","EBY40UCQ4SN","Simone, Daria","Gomez","Amet Ante Vivamus Corp."),("Vincent","SBG46BYP4WF","Herman, Scarlett","Hahn","Id LLC"),("Chava","TLP32IFX7CY","Leslie, Sebastian","Miles","Vitae Erat Vel Industries"),("Colin","WTI58ANB2PF","Alea, Giselle","Moss","Eu Enim Etiam Associates"),("Joel","CDG89TKD5EV","Odessa, Avram","Finley","Purus Corp."),("Unity","SYX58XYE4YT","Solomon, Bryar","Saunders","Lacus Cras Inc."),("Remedios","POG79CYV4CY","Lee, Selma","Rosario","Enim Gravida Sit Associates"),("Flynn","NQY57FGJ3EJ","Sierra, Helen","Sheppard","Pellentesque Industries"),("Jerome","HNE99WOO8KO","Jermaine, Tanya","Hobbs","Quam Vel Institute"),("Keane","PON97SRC1RC","Leonard, Tallulah","Hurst","Ultricies Foundation");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Jared","BGP06OWU7ZR","Tiger, Joy","Justice","Lorem Corporation"),("Katelyn","ASG58SQP7BK","Molly, Mariam","Reynolds","Odio Aliquam Vulputate Company"),("Amity","RBG29HJQ7SJ","Stella, Caldwell","Small","A Scelerisque Corporation"),("Martena","DCH13RZB7AB","Kelsie, Iris","Boyd","Sed Diam Lorem Limited"),("Brooke","CNK39ZUI9PX","Nelle, Dylan","Molina","Vitae Limited"),("Maite","KOR70VNT3HW","Giacomo, Keaton","Day","Lorem Corp."),("Richard","EGW34MFL0DC","Katelyn, Wallace","Harris","Nec Corp."),("Henry","AUY00LTE8GF","Sonya, Quinlan","Lester","Porttitor Corp."),("Veda","DBV78REL9PO","Abbot, Mannix","Little","Feugiat Foundation"),("Tucker","WFC25URT3TL","Anthony, Elizabeth","Hill","Erat Vivamus Nisi Industries");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Mikayla","ESM29CRX2UG","Xenos, Harlan","Bradshaw","Consectetuer Ipsum Nunc Foundation"),("Sonia","ZNN81ZSJ9XK","Jemima, Fleur","Steele","Erat Volutpat Nulla Company"),("Alvin","AQD24AYR0DE","Keith, Anne","Hess","Venenatis LLC"),("Celeste","JXI44BPM8OH","Rama, Kyla","Sutton","Scelerisque LLC"),("Ria","OUW26JUN1XA","Raja, MacKenzie","Ellison","Nisl Arcu Iaculis LLP"),("Candice","JQB46NBC8BR","Kaye, Karyn","Mercado","Congue A Corp."),("Hector","OIY65JJK4XJ","Shafira, Jonah","Burgess","Interdum Curabitur Dictum Limited"),("Kareem","ZYQ91NAJ7AN","Amity, Guy","Walsh","Vestibulum Mauris Magna Corp."),("Yvette","OZZ31OLF0KN","Clementine, Marshall","Robles","Nisl Industries"),("Kenyon","QMK76DMB5RX","Robert, Maggy","Hendrix","Morbi Neque Industries");
INSERT INTO `User` (`username`,`password`,`name`,`surname`,`position`) VALUES ("Faith","TDI28XDF0HR","Zeus, Porter","Sanchez","Ligula Ltd"),("Ariel","HKK59QMQ9QY","Randall, Colin","Hendricks","Rutrum Urna Associates"),("Calista","XVF72SIF7ZL","Maxwell, Brandon","Poole","Ac Nulla In PC"),("Wyatt","FYW88WER7XO","Salvador, Madaline","Wooten","Orci Foundation"),("Erica","STC45RVU9ID","Rowan, Tana","Mclaughlin","Tellus Imperdiet Industries"),("Buckminster","ECS50GGO2EO","Holmes, Quynn","Kaufman","Mi Pede Ltd"),("Louis","ZMJ82VWV4CI","Rylee, Dominic","Walsh","Diam Dictum Sapien Company"),("Dexter","RKL61THP0RY","Quinn, Katelyn","Avila","Quis Institute"),("Beau","PAL27CDS3UI","Rigel, Jessamine","Reed","Sapien Limited"),("Shad","ZHP92NYC7DB","Ezra, Medge","Austin","Libero Corp.");


/* Staff */

INSERT INTO Staff (staff_id) SELECT user_id FROM User LIMIT 80;

/* Business_Partner */

INSERT INTO Business_Partner (partner_id, represents) SELECT user_id, position FROM User ORDER BY user_id DESC LIMIT 20;


/* Team */

INSERT INTO `Team` (`name`,`status`) VALUES ("Indianapolis",3),("Woodlands County",5),("Villafranca in Lunigiana",9),("King Township",4),("Morwell",3),("Lincoln",8),("Bünyan",10),("San Joaquín",1),("Harnoncourt",3),("Maiolati Spontini",7);

/* Meeting */

INSERT INTO `Meeting` (`creator_id`,`date`,`end_time`,`start_time`) VALUES (1,"2018-02-25","06:42:11","14:42:48"),(2,"2017-09-16","08:28:06","02:44:43"),(3,"2017-08-24","18:17:56","09:55:37"),(4,"2017-08-07","08:33:49","18:28:40"),(5,"2017-06-29","05:16:41","19:09:14"),(6,"2018-03-08","13:43:31","23:42:05"),(7,"2017-12-11","14:20:08","18:24:34"),(8,"2018-07-04","18:26:10","08:59:14"),(9,"2018-01-10","05:21:04","00:44:35"),(10,"2019-02-14","00:38:15","06:19:15");
INSERT INTO `Meeting` (`creator_id`,`date`,`end_time`,`start_time`) VALUES (11,"2018-09-29","13:20:18","13:49:05"),(12,"2018-11-06","18:04:26","09:06:30"),(13,"2019-01-22","01:58:36","18:04:55"),(14,"2019-02-24","12:06:55","15:02:06"),(15,"2018-05-05","15:44:47","19:49:40"),(16,"2018-12-26","06:21:24","21:34:28"),(17,"2017-11-24","07:43:38","04:49:26"),(18,"2017-05-14","22:30:40","05:50:40"),(19,"2017-10-04","12:14:52","10:31:29"),(20,"2018-12-27","07:58:54","07:16:36");

/* Available_Resource */

INSERT INTO `Available_Resource` (`room_no`,`capacity`,`address`,`building_name`) VALUES (10,91,"P.O. Box 574, 1767 Nunc Ave","Palestine, State of"),(1,82,"6526 Fringilla Road","Romania"),(8,77,"Ap #226-956 Quisque Av.","Saint Vincent and The Grenadines"),(3,10,"819-3714 Odio Road","South Sudan"),(10,18,"Ap #120-6951 Sodales Street","Eritrea"),(5,72,"873-3090 Sagittis Road","Estonia"),(4,95,"P.O. Box 226, 7016 Mattis St.","Burkina Faso"),(3,16,"P.O. Box 973, 7797 Id St.","Croatia"),(3,14,"P.O. Box 847, 5511 Sem St.","Saint Barthélemy"),(8,63,"565-4373 Mauris Av.","New Caledonia");
INSERT INTO `Available_Resource` (`room_no`,`capacity`,`address`,`building_name`) VALUES (9,46,"447-2977 Nunc Ave","Panama"),(2,56,"3829 At Av.","Namibia"),(5,98,"P.O. Box 458, 5479 Odio. Rd.","Bosnia and Herzegovina"),(3,54,"Ap #995-8521 Ullamcorper St.","Poland"),(9,10,"4300 Vestibulum. St.","Malawi"),(9,97,"4969 Ut Rd.","Eritrea"),(2,68,"921-2436 Odio St.","Germany"),(2,64,"Ap #471-5346 Nascetur Ave","Mauritius"),(2,70,"Ap #580-5850 Nunc St.","Thailand"),(1,94,"Ap #980-1600 Maecenas Av.","Wallis and Futuna");

/* Facility */

INSERT INTO `Facility` (`name`,`cost`) VALUES ("quis",334),("egestas",377),("tellus",384),("malesuada",437),("Duis",200),("est",236),("et",185),("id,",168),("dolor,",492),("arcu.",245);

